name: jellopass
version: '2.1.0'
summary: A secure password manager
description: |
  JelloPass is a command-line password manager that stores your passwords securely.
  It uses the Fernet encryption library to encrypt your passwords, and now saves them
  in an encrypted folder for added security.

grade: stable
confinement: strict

apps:
  jellopass:
    command: bin/jellopass
    plugs: [home, removable-media]

parts:
  jellopass:
    source: .
    plugin: python
    python-version: python3
    stage-packages:
      - python3-cryptography
